# Generated by Django 5.2.1 on 2025-05-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_approve', 'Can approve tickets'), ('can_mark_completed', 'Can mark work as completed')]},
        ),
    ]
